default: &default
  adapter: postgresql
  encoding: unicode
  username:  <%= ENV.fetch('GIF_DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('GIF_DATABASE_PASSWORD') { 'postgres' } %>
  host: <%= ENV.fetch('GIF_DATABASE_HOST') { 'localhost' } %>
  pool: 5

development:
  <<: *default
  database: gif_development

test: &test
  <<: *default
  database: gif_test

staging:
  <<: *default
  database: <%= ENV['GIF_DATABASE_URL'] %>

production:
  <<: *default
  database: <%= ENV['GIF_DATABASE_URL'] %>
